### ISSUE TITLE
Error ATM-Raub

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#117]
![image](https://github.com/user-attachments/assets/f289bdf5-6398-49c1-b0bc-9b8791bd3a9c)

Kam bei Jordan wohl random, während er im Teamjob war - hat aber keinen ATM angewählt gehabt

**Comment by FCJuna** [comment]
Ey ich hab nur auf Jordan gehört, hahahahah

**Comment by NelsStorch** [comment]
lvc ersetzt
