### ISSUE TITLE
Aduty Bug

### ISSUE THREAD

**Issue by JordanFuCi** [FCLucas1/furious-bugs#119]
Nach dem verlassen der Aduty Kleidung (über Admin Menü) bin ich nur noch in weißem Shirt, blauer Hose sowie ohne Haare und Bart.

**Comment by JordanFuCi** [comment]
![Bild_2024-11-14_125826227](https://github.com/user-attachments/assets/0f675ab8-8d04-4a36-a7dc-0439145957c5)

**Comment by NelsStorch** [comment]
Fix in aduty eingebaut muss noch getestet werden

**Comment by NelsStorch** [comment]
Ist gefixt und getestet
