### ISSUE TITLE
Dead Loop

### ISSUE THREAD

**Issue by JordanFuCi** [FCLucas1/furious-bugs#120]
Man fliegt immer wieder raus durch folgenden Fehler

![Screenshot 2024-11-14 130023](https://github.com/user-attachments/assets/83220cca-24f6-46f6-b96b-7275c45ee155)
 
[CfxCrashDump_2024_11_14_12_00_24.zip](https://github.com/user-attachments/files/17748225/CfxCrashDump_2024_11_14_12_00_24.zip)

**Comment by NelsStorch** [comment]
# RTX GYM darf nicht gerestartet werden
