### ISSUE TITLE
Sammeln nach Tod

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#13]
Das Sammeln (und evtl. das Verarbeiten) von Objekten geht trotz Bewusstlosigkeit weiter, selbst wenn man vom Ort entfernt wird

**Comment by FCLucas1** [comment]
schauen ob man mit dem event aus der documentation folgendes bauen kann:

Jedes mal wenn der Spieler ein Item farmt wird gecheckt ob dieser tot ist, sollte dies der fall sein wird einmal die e taste ausgelöst

RegisterNetEvent("farming_creator:farms:completed", function(playerId, farmId, givenItems)
    -- An example for a xp system
    TriggerEvent("xp_system:addXp", playerId)
end)

https://documentation.jaksam-scripts.com/

**Comment by FCLucas1** [comment]
ist behoben
