### ISSUE TITLE
V3 Bot postet zu oft

### ISSUE THREAD

**Issue by JordanFuCi** [FCLucas1/furious-bugs#147]
Habe die erste Fraktion (LSMD) über den Bot eintragen wollen, dieser hat mir angezeigt die Anwendung würde nicht reagieren und gleichzeitig hat er die Meldung 4 mal raus gehauen.

![Bild_2024-11-21_144955876](https://github.com/user-attachments/assets/77dbf18c-197a-4f14-88ac-21571d795b28)

![Bild_2024-11-21_145018161](https://github.com/user-attachments/assets/d30c1d85-32cb-4cdf-bf06-c955276ad146)

**Comment by FCLucas1** [comment]
@NelsStorch

**Comment by NelsStorch** [comment]
@JordanFuCi War das nur beim LSMD oder bei den Anderen dann auch?

**Comment by FCLucas1** [comment]
@NelsStorch  war nur beim lsmd also bei der ersten ankündigung
