### ISSUE TITLE
snipe Menü givecar

### ISSUE THREAD

**Issue by JordanFuCi** [FCLucas1/furious-bugs#149]
Ich wollte Luzi ein Motorrad geben und habe über das U Menü Give Car gewählt, seine ID sowie das Modell eingegeben.

Im Anschluss befindet sich das Fahrzeug in meiner Garage statt in seiner.

**Comment by JordanFuCi** [comment]
Nach ausparken der Fahrzeuge sind diese ohne Tank und müssen erst ein refill bekommen um gestartet zu werden

**Comment by FCLucas1** [comment]
wir nutzen auch für give car nicht das u menü sondern den /givecar befehl
