### ISSUE TITLE
Jobmenü

### ISSUE THREAD

**Issue by JordanFuCi** [FCLucas1/furious-bugs#150]
Einzahlung auf firmen Konto klappt erst nach dem dritten Versuch. Folgende Fehler wurden gemeldet:

![Bild_2024-11-22_013715450](https://github.com/user-attachments/assets/99904d7e-1a21-43df-a0fa-7cdf629cb16a)

![Screenshot_2024-11-22_013424](https://github.com/user-attachments/assets/34b7ddfb-d5f1-425d-8a9d-af7f6a273e9d)

**Comment by FCLucas1** [comment]
Geht wieder ohne probleme, menu default von ws runtergeschmissen und eigenes design gemacht
