### ISSUE TITLE
staatlicher Frak Autohändler nicht zu sehen

### ISSUE THREAD

**Issue by JordanFuCi** [FCLucas1/furious-bugs#151]
Egal in welchen Führungsebenen ich mich und Jeffrey bei unseren staatlichen Fraks eintrage ist derFahrzeughändler nicht zu sehen auf der Karte.

**Comment by NelsStorch** [comment]
Mit welchem job ist er eingeloggt?

**Comment by JordanFuCi** [comment]
Wir haben MD und PD probiert

**Comment by JordanFuCi** [comment]
Er war vorher aber ohne Job

**Comment by JordanFuCi** [comment]
Hab ihm vorher nur seine IC Rechte gegeben, weiß nicht ob das damit zusammen hängen könnte

**Comment by NelsStorch** [comment]
Er muss mit dem entsprechenden Job einloggen da die Leistung sich ja nicht so oft ändern (ja off duty ist auch drin)

**Comment by JordanFuCi** [comment]
check
