### ISSUE TITLE
#49 patrickkns

### ISSUE THREAD

**Issue by FCLucas1** [FCLucas1/furious-bugs#197]
Man Verarbeitet trotz vollem Inventar weiter, verliert die Materialien aber bekommt kein Endprodukt. Wäre vorteilhaft wenn das Arbeiten sobald das Inventar voll ist abbricht.

**Comment by FCJuna** [comment]
Was wurde verarbeitet?

**Comment by FCJuna** [comment]
Gewichte sind zum Restart angepasst um die Überladungswahrscheinlichkeit zu verringern - Stopp bei der Überproduktion können wir aktuell nicht umsetzen
