### ISSUE TITLE
Dart

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#20]
"Spieler 2" sieht beim Dart-Spielen teilweise nicht, wohin er wirft - weil die wankende "Hilfslinie" verschwindet
Außerdem ist der Aktionsradius immer noch zu klein, sodass man mit der Scheibe kuscheln muss, um ein Spiel zu starten

**Comment by FCLucas1** [comment]
funktioniert, konnten fehler nicht reproduzieren
