### ISSUE TITLE
#52 the_nexus_tv

### ISSUE THREAD

**Issue by FCLucas1** [FCLucas1/furious-bugs#200]
schlüsse übergabe spam

**Comment by FCLucas1** [comment]
was spamt da genau?

**Comment by FCJuna** [comment]
Pasiert gelegentlich durch das Handy - entweder das Schlüsselding auf eine andere Taste binden oder versuchen den Spam zu beenden. Ich bin mir nicht mehr sicher aber entweder musste man einmal schlagen (also linksklick) oder I drücken - probier das bitte nächstes Mal aus. ESC usw. hatten da nicht geholfen

**Comment by FCLucas1** [comment]
Wird vermutlich behoben sein mit telfon wechsel
