### ISSUE TITLE
Essen / Props

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#24]
Einige Speisen haben gar keine Props beim Konsumieren, andere schon

Einige Speisen müssen bei der Sättigung angepasst werden - manche Snacks geben so viel Hunger wie eine Hauptmahlzeit
Zutaten für Gerichte sollten verschwindend wenig geben an Essen / Trinken, damit sie nicht abused werden

**Comment by FCLucas1** [comment]
Props gefixt
