### ISSUE TITLE
Panzerwagen / Gruppe 6

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#26]
Der scheint nachts immer mal wieder zu starten und hat für den geringen Aufwand (mit Bohrer aufknacken) zu viel Schwarzgeld geladen (um die 70k). Manchmal scheint er gar nichts zu enthalten

Manchmal verschwindet der random von der Map und taucht wieder auf usw.

**Comment by FCLucas1** [comment]
Transporter etwas angepasst
