### ISSUE TITLE
Schiebetüren öffnen verspätet / gar nicht

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#34]
Alle Schiebetüren öffnen sich auch nach auffschließen entweder extrem schwergängig oder gar nicht - im PD die Zellentüren muss man mit Gewalt auftreten

**Comment by NelsStorch** [comment]
Evt können wir uns das mal anschauen:
https://www.youtube.com/watch?v=Pp2mMvmjxoI&t

**Comment by FCLucas1** [comment]
gelöst
