### ISSUE TITLE
Probleme Holzfällerjob

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#35]
Der LKW steckt nach dem Entladen der Holzstämme oben am Fließband fest und lässt sich nicht mehr bewegen.
Die Stämme werden abgeladen und die Meldung erscheint, dass man fertig ist - der LKW lässt sich jedoch nicht mehr wegfahren.

Außerdem erscheint der Container mit den verkaufbaren Spähnen manchmal nicht.

**Comment by FCLucas1** [comment]
Konnte keinen fehler festellen
