### ISSUE TITLE
Gefahrenstufen-System einführen

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#40]
Manni hat den Vorschlag geäußert ein Gefahrenstufen-System zu entwickeln, dass dann evtl. über ein Script für alle Bürger sichtbar wird oder vorerst im Discord gepostet wird

Warnstufen 1 - 4
jede Warnstufe hat andere Konsequenzen für die Bürger

**Comment by FCLucas1** [comment]
ist in arbeit
