### ISSUE TITLE
FFA Waffenbug// Fehlende Munition

### ISSUE THREAD

**Issue by Onlinedexx** [FCLucas1/furious-bugs#48]
1. Beim betreten von FFA und anschließendem ziehen einer X-Beliebigen Waffe und direkten ausführen des Befehls /quitffa behält man die zuvor ausgewählte Waffe aus FFA in der normalen RP Welt. 

2. Für die Schrotflinten gibt es keine Munition im FFA da diese noch auf Gummigeschosse getriggert sind.

**Comment by FCLucas1** [comment]
ticket bei unique aufgemacht

**Comment by FCLucas1** [comment]
behoben
