### ISSUE TITLE
PD-Spind Kapazität

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#51]
Die PD-Spinde haben aktuell nur eine Kapazität von 5kg - das ist zu wenig für unsere Dienstausrüstung

![image](https://github.com/FCLucas1/furious-bugs/assets/171638802/a21e0498-6a37-451d-93e0-02951253d059)
![image](https://github.com/FCLucas1/furious-bugs/assets/171638802/2990efcc-9f2d-47d2-8300-00aef25437b1)

**Comment by FCLucas1** [comment]
gewicht angepasst
