### ISSUE TITLE
Jobscreator defekt?

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#52]
Im Jobscreator sind Lager usw. nicht mehr sichtbar 
![image](https://github.com/FCLucas1/furious-bugs/assets/171638802/230fe488-a8ab-4326-ae01-afef36b5bf57)
![image](https://github.com/FCLucas1/furious-bugs/assets/171638802/b1e931c7-3263-48c5-b878-e93c6fdbdeea)

**Comment by FCLucas1** [comment]
gelöst, nix beta version nutzen
