### ISSUE TITLE
Emote-Menü

### ISSUE THREAD

**Issue by FC-Manni** [FCLucas1/furious-bugs#54]
Zu viele 18+ Emotes müssen **unbedingt** entfernt werden

**Comment by FC-Manni** [comment]
Emoteliste

Tanz Emotes 
alles i.O.

Prop Emotes
jerkf (211) 18+Emote
pornmag (304) 18+Emote
pornmag2 (305) 18+Emote
pornmag3 (306) 18+Emote
pornmag4 (307) 18+Emote
pornmag5 (308) 18+Emote
pornmag6 (309) 18+Emote
pornmag7 (310) 18+Emote
watchstripper2 (475) 18+ Emote

Emotes3.0
mopose (599) 18+Emote
wall2 (623) funktioniert nicht

Emotes4.0
nekosex (319) 18+Emote 
nekosex2 (320) 18+Emote 
nekosex3 (321) 18+Emote 
nekosex4 (322) 18+Emote 
nekosex5 (323) 18+Emote 
nekosex6 (324) 18+Emote 
nekosex7 (325) 18+Emote
sexo     (395) 18+Emote
sexo2    (396) 18+Emote 

Emotes5.0
alles i.O.

Geteilte Emotes
giveblowjob (56) 18+Emotes
receiveblowjob (169) 18+Emotes
sex (172) 18+Emotes
sex2 (183) 18+Emotes
sex3 (184) 18+Emotes
sex4 (185) 18+Emotes
sex5 (186) 18+Emotes
sex6 (187) 18+Emotes
sex7 (188) 18+Emotes
sex8 (189) 18+Emotes
sex9 (190) 18+Emotes
sex10 (173) 18+Emotes
sex11 (174) 18+Emotes
sex12 (175) 18+Emotes
sex13 (176) 18+Emotes
sex14 (177) 18+Emotes
sex15 (178) 18+Emotes
sex16 (179) 18+Emotes
sex17 (180) 18+Emotes
sex18 (181) 18+Emotes
sex19 (182) 18+Emotes
sex20 (184) 18+Emotes
sex21 (185) 18+Emotes
sex22 (186) 18+Emotes
streetsexfemale (230) 18+Emote
streetsexmale (231) 18+Emotes

Emotes
fspose  (133) 18+Emotes
fspose2 (134) 18+Emotes
fspose3 (135) 18+Emotes
pee     (278) 18+Emotes
pee2    (279) 18+Emotes
scratch (317) 18+Emotes
showboobs (329) 18+Emotes
showboobs2 (330) 18+Emotes
watchstripper (454) 18+Emotes

**Comment by FCLucas1** [comment]
erledigt sind entfernt zu 2 uhr
