### ISSUE TITLE
Tuning East Customs

### ISSUE THREAD

**Issue by JordanFuCi** [FCLucas1/furious-bugs#58]
"Wir haben bei East Customs folgendes Problem und zwar können wir nicht auf das Tuning Menü zugreifen. Normalerweise setzten wir uns in Auto und drücken die taste Z und dann öffnet sich das Menü aber die Taste wird uns noch nicht einmal angezeigt auf wenn wir vor dem Auto stehen können wir nichts eingeben und sehen nichts was wir eingeben müssen"

**Comment by JordanFuCi** [comment]
update Temporär können einzelne Mitarbeiten wohl wieder Tunen besonders wenn sie ein Powernap machen

**Comment by FCLucas1** [comment]
sollte behoben sein
