### ISSUE TITLE
Minenjob mehrere Fehler

### ISSUE THREAD

**Issue by JordanFuCi** [FCLucas1/furious-bugs#59]
Minenjob bugt aktuell:

- Weiter hacken bis 100% 
- Schienen Bau kommt nicht hinterher 
- Props in der Hand dauerhaft
- Licht noch hinten drauf nach Job Ende
- Fahrstuhl bug -> Glitch durch die Map

**Comment by FCLucas1** [comment]
Behoben durch entfernen des FPS menüs
