### ISSUE TITLE
Abschleppen mit /abschleppen

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#62]
Der Befehl /abschleppen (Konfiszierung über Zeit im Abschlepphof) löst zwar aus, zieht aber keine Fahrzeuge weg - es entsteht kein Fehler in der F8-Konsole
- war jetzt vorallem bei Fraktionsautos von Crimefraks

**Comment by FCLucas1** [comment]
Ticket bei OKOK aufgemacht
