### ISSUE TITLE
Türen im PD

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#63]
Die Türen im PD sind ständig komplett blockiert und öffnen nicht, der Doorscreator behauptet dann, die Türen seien schon irgendwo vergeben. Das Problem betrifft nur Türen ohne Schloss

**Comment by FCLucas1** [comment]
Liegt am server Cache, ich bin dran an einer lösung

**Comment by FCLucas1** [comment]
Behoben mit einem Doorlock, evtl behebt es sich noch weiter mit auslagern des server cache
