### ISSUE TITLE
Immobilien-Garagen

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#64]
Die Immobilien-Garagen sind nicht nutzbar und somit muss man, je nach Grundstück, ultra weit in die Stadt laufen.

Man kann weder ein- noch ausparken.

**Comment by NelsStorch** [comment]
Ging bei mir.
Habe jetzt aber vollständig auf okok umgestellt. müssen nach 5 Uhr nochmals schauen.
