### ISSUE TITLE
Inventar-Bug beim Durchsuchen

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#66]
Beim Durchsuchen von Personen kommt es häufiger mal vor, dass man das inventar der anderen person nicht öffnen kann
Dabei kommen unterschiedliche "Fehler-Anzeigen" aber keine Meldungen in der F8-Konsole
![image](https://github.com/FCLucas1/furious-bugs/assets/171638802/253a8119-d5a9-4910-bc5e-a770bea3927e)
![image](https://github.com/FCLucas1/furious-bugs/assets/171638802/da9c05fd-c841-4bfe-a238-b79c9b257bec)
(Person war bereits gefesselt, neues Fesseln hilft auch nicht)

**Comment by FCLucas1** [comment]
könnte auch hier am server cache liegen

**Comment by NelsStorch** [comment]
@FCLucas1 könnten das auf force umstellen könnte aber auch missbraucht werden z.B. wenn jemand wegrennt.

**Comment by FCLucas1** [comment]
> @FCLucas1 könnten das auf force umstellen könnte aber auch missbraucht werden z.B. wenn jemand wegrennt.

kann man da einen radius bestimmen wie weit man das inv dann öffnen kann?

plus es gibt ja einen export von jobscreator ob der spieler gefesselt ist den man nutzen kann
