### ISSUE TITLE
Idle-Animation Männer

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#68]
Männer hampeln beim Idlen ganz schön rum, während Frauen sich nicht bewegen
Wäre besser, wenn die Männer auch eher ruhig sind und nicht so wild rumhampeln würden

**Comment by FCLucas1** [comment]
Ticket beim ersteller des Emote menüs aufgemacht

**Comment by FCLucas1** [comment]
Ist zum restart entfernt
