### ISSUE TITLE
HUD Icons

### ISSUE THREAD

**Issue by FC-Manni** [FCLucas1/furious-bugs#69]
Alle Waffen Icons erstellen und hinzufügen
Bitte unten eintragen welche Waffen kein Icon haben

**Comment by FCJuna** [comment]
Pistol MK2
Schlagring
Messer / Knife
Compact Rifle
Pistol
Combat Pistol
SMG
Special Carbine MK2

**Comment by FCLucas1** [comment]
erledigt, ist ab 2 uhr aktiv
