### ISSUE TITLE
Lackierkabine + DJ-Pult EC

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#74]
Bitte nach dem Restart noch das Prop umsetzen, da das DJ-Pult weiter nach rechts gewandert ist

**Comment by NelsStorch** [comment]
> Bitte nach dem Restart noch das Prop umsetzen, da das DJ-Pult weiter nach rechts gewandert ist

@FCJuna du kannst den prop auch umsetzen ist mit mymapbuilder gemacht evt mit Jeffery oder chris schauen die hatten den gebaut

**Comment by FCLucas1** [comment]
erledigt

**Comment by NelsStorch** [comment]
Nochmals besser gemacht
