### ISSUE TITLE
Übersetzungen Dealership

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#76]
Im Dealership gibt es "Übersetzungsfehler", bspw. wenn man Koordinaten umsetzt oder bestimmte Punkte nutzen will
![image](https://github.com/FCLucas1/furious-bugs/assets/171638802/867d4121-1b8c-4ad3-9ade-168870041572)

**Comment by FCLucas1** [comment]
behoben ab restart
