### ISSUE TITLE
Autodiebstahl

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#77]
Der Autodiebstahl despawned sich immer noch manchmal nach dem Auftauchen - war vorhin erst wieder. Dann bleiben einige Autos die drauf sein sollten einfach zurück.

**Comment by FCJuna** [comment]
Kann es sein, dass das mit dem Abschleppsystem kollidiert?

**Comment by NelsStorch** [comment]
> Kann es sein, dass das mit dem Abschleppsystem kollidiert?

Nein danke ich nicht. Denke liegt eher an Advents parking oder anticheat

**Comment by FCLucas1** [comment]
advanced parking Fixdeletevehicles datei eingebaut muss man nach 5 uhr mal prüfen

**Comment by FCLucas1** [comment]
entfernt
