### ISSUE TITLE
Führerscheine nicht sichtbar bei PKW-Lizenz-Entzug

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#85]
Sobald einem die PKW-Lizenz entzogen wird, sieht man seine anderen Führerscheine nicht mehr

**Comment by NelsStorch** [comment]
Erledigt

**Comment by NelsStorch** [comment]
Checken nach Restart

**Comment by FCJuna** [comment]
Führerscheine sind jetzt gar nicht mehr sichtbar!
