### ISSUE TITLE
Fahrschule

### ISSUE THREAD

**Issue by FCJuna** [FCLucas1/furious-bugs#88]
Geschwindigkeiten anpassen an das Gesetzbuch IC und schauen, ob alle Geschwindigkeitszeichen angezeigt werden korrekt

**Comment by FCJuna** [comment]
Auf Parkplätzen: 50 km/h
Innerhalb geschlossener Ortschaften: 80 km/h
Außerhalb geschlossener Ortschaften: 120 km/h
Auf High- und Freeways: 200 km/h

**Comment by NelsStorch** [comment]
Alles gemacht ausser Ton datein
